default-extensions: GADTs
library:
  source-dirs: src
tests:
  data-structures-test:
    source-dirs: test
    main: tests.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-structures
copyright: 2020 spp
maintainer: foldr.spp at gmail.com
dependencies:
- containers
- stm
- vector
- base
- text
- bytestring
- vector
- random
- mtl
- mwc-random
- primitive
- array
- unordered-containers
- hashable
- psqueues
- generic-lens
- lens
- smallcheck
- tasty
- HUnit
- tasty-smallcheck
- tasty-hunit
- QuickCheck
- quickcheck-text
- quickcheck-instances


name: data-structures
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: spp
github: songpp/data-structures
license: BSD3
executables:
  data-structures-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-structures
description: Nothing left here
